services:
  - type: web
    name: desmos-art-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DEBUG
        value: false
